### ISSUE TITLE
Solver does not support sums with double-valued cells

### ISSUE THREAD

**Issue by gnidan** [sigh/Interactive-Sudoku-Solver#4]
A somewhat common Sudoku variant I've noticed and enjoy is the use of "value" instead of "digit" for some constraints. For instance, [a puzzle I recently discovered](https://sudokupad.app/giuk6t4rfg) doubles the value of every digit in box 5, which it pairs with a killer cage of sum 70. As far as I could tell, there was no way of entering such a constraint into this application.

I figured I would open this issue in case this is an interesting use case, although I do fear that it might require some amount of reworking the code (I did take a quick look and found more architecture than I was prepared to touch ;).

(The example puzzle I linked also introduces a new spin on variants that your application does not support, such as renban line(s) that may or may not even connect, and the need to figure out what cells belong to the 70 cage in the first place... but these are pretty unique to this puzzle, in contrast with the digit/value distinction that comes up pretty commonly.)

**Comment by mistocat** [comment]
Hi,

I am a complete amateur programmer but I have used this
repository to teach myself javascript over the past few
months and I have made a few custom constraints - it's
not as daunting / dense as it first looks and if I can do
it then i'm sure you can too if you have any experience.
(please anyone correct me if I'm wrong on anything).

Since killer cages are just Sum constraints with an 'AllDifferent'
constraint in ISS, you could just implement a new SudokuConstraintHandler
that can hold logic for dealing with the doubler cells.
You would have to be careful with the enforcement
as the LookupTables / SumHandlerUtil cant handle repeated values and these
speed up the solver massively in killers. (i.e. be creative with enforcement
of the new constraint and try to optimize as much as possible for solving,
the solver is super quick regardless of using the lookup tables but
only when you are creative with the implementation)

If you are new to making a custom constraint in ISS, it is
not as difficult as you might think. Search the whole repository for
something like 'cage' or another constraint (with a handler in handlers.js like quad)
and basically copy it and adjust that code across the files. The handler is
/ will be needed to optimize as you cant use regular killer cage, but you
can use the drawing function for cages to draw yours if you want. (display.js holds 
drawKillerCage function but in render_page within ConstraintManager you
specify what drawing function is used to display your constraint.)
render_page.js, display.js, sudoku_builder.js and handlers.js are the main
files you will edit overall, sometimes index.html but just follow the path of
other constratints. For your constraint it should follow a simple path
that will add it to the list of others in the selection box so not that complex.
Main logic rests in enforceConsistency part of the handler class, that is where you
need to shine ;) 

If you wanted to implement something broader (say schrodinger cells which is similar 
to your constraint issue) then it would be a more complicated process.
I am trying to integrate them at the moment, finding it hard since its
a global constraint affecting many cells but it's not impossible. The tricky parts I have
found are how to let the solver attempt logic on the constraint
during the solve at optimal times since if you just let it attempt
everything it reduces to a regular slow solver despite general cleverness he
has written for cell selection etc. I would suggest a tiering system of
when it could look for cell values aggressively - like when certain conditions are
met in areas around the constraint. I have no clue if this is the best way,
but it's the only way I have gotten things like Circle Counters and
multiple choice lines to work. (eg: is the line a  Renban, Whisper or RegionSum)

If you are not used to using bitmasks / bitwise operations then
just use regular numbers and arrays and go back later to optimize with bitmasks.
It is way slower but I suggest you get it roughly working and in the UI first
if you are totally new to it. Also, this guys code is mega-optimized so it will
probably take a while to learn to optimize as good as him !

How you could input the constraint in the UI:

- Select cells for the cage AND select cells for the doubler cells in the
  usual way you would for killer cages.
- Use the input box to define a sequence which represents the information.
  This is not a pretty way of doing it but it works.
  I have used sequences in the past for custom constraints (not equal sums etc)
  as i dont care how it looks in the UI, i just want the ability to input in
  a relatively quick way (someone good at UI would be better ofc ..). You just
  need to parse the input so you can extract the info needed when passing to
  the new handler you are making.
- If you input a sequence of like 5-3-12 it could mean first 5 cells are cage, the 3 
	are the doubler cells, 12 is the sum. Then handle special cases for overlap etc,
	pretty simple.

Personally I would prefer if things like loops / paths we're worked on before looking at digits v values 
as they can use mostly just digits - I assume Sigh has a real job so working time on this is probably sparse ...

Good luck !

**Comment by sigh** [comment]
The general problem of having arbitrary values is a hard one. More than any architectural changes, many of the constraint handlers would need to be updated to take that into account, and its probably not possible to do it efficiently for all constraints.

That said, it should be possible for your specific problem:
* Renban can be expressed as a set of binary constraints between each pair of cells. The solver allows you to add custom binary constraints. Have a look at the implementation of renban in sudoku_builder.js. It gets more complicated when there are different values, but it is feasible.
* Sums with double values can be simulated by having a cell appear twice in the list of cells. Thisis not possible in the UI, but is a valid constraint string. The sum handler doesn't currently handle this case, but I think it only requires minor changes to fix.

I'll have a look at allowing this in the Sum handler, and see if I can get this puzzle to work (with all the constraints visible/known). However, I don't know if there's a clean way to add that to that to the UI.

If you have more examples, then we can consider if there are generalizations which are tractable.

As you noted, the issue of hidden constraints (or generally, state outside of the cell digits) is not something the solver handles, and I think would require invasive changes to the core of the solver.

**Comment by sigh** [comment]
I updated the Sum and Cage constraints so they can contain the same cell multiple times, simulating duplicate values. It was more fiddly than I expected, so please let me know if you see any bugs.

As mentioned before, I don't think I'll make it possible from the UI, so you'll have to construct the constraint string yourself. The renban is possible to construct in the UI, but very tedious, so I'd recommend doing that programmatically as well.

Here is what the Event Horizon puzzle looks like along with code that will generate the constraint string:

* https://sigh.github.io/Interactive-Sudoku-Solver/?q=.Cage~20~R1C2~R2C2~R2C1.Cage~20~R4C2~R4C3~R4C4~R4C4.Cage~20~R8C2~R8C1~R9C1.Cage~10~R1C8~R2C8~R2C9.Cage~0~R6C6~R6C7~R6C8~R6C6.Cage~70~R2C5~R3C5~R4C5~R5C5~R6C5~R7C5~R8C5~R5C4~R5C6~R4C5~R5C5~R6C5~R5C4~R5C6.Sum~30~R1C9~R2C8~R3C7~R4C6~R5C5~R6C4~R7C3~R8C2~R9C1~R4C6~R5C5~R6C4.Sum~30~R1C2~R2C3~R3C4~R4C5~R5C6~R6C7~R7C8~R8C9~R4C5~R5C6.Sum~30~R1C6~R2C5~R3C4~R4C3~R5C2~R6C1.BinaryX~_v-7-_v-7-_v-D~_renban-single~R6C2~R7C3~R7C4~R3C6~R2C5.BinaryX~eoH75ev378GvwD~_renban-double~R4C6~R5C6~R5C5~R6C4~R6C5.Binary~fwD-oH-ZP-7e-H~_renban-mixed~R6C2~R4C6~~R6C2~R5C6~~R6C2~R5C5~~R6C2~R6C4~~R6C2~R6C5~~R7C3~R4C6~~R7C3~R5C6~~R7C3~R5C5~~R7C3~R6C4~~R7C3~R6C5~~R7C4~R4C6~~R7C4~R5C6~~R7C4~R5C5~~R7C4~R6C4~~R7C4~R6C5~~R3C6~R4C6~~R3C6~R5C6~~R3C6~R5C5~~R3C6~R6C4~~R3C6~R6C5~~R2C5~R4C6~~R2C5~R5C6~~R2C5~R5C5~~R2C5~R6C4~~R2C5~R6C5.
* https://gist.github.com/sigh/8771bc786e451df590e4fecc58e4d87c

Note, this code is not guaranteed to be stable across versions, but I'm happy to introduce more convenient functions to make programmatic construction more ergonomic.

**Comment by sigh** [comment]
Given that the update to the `Sum` handler[^1] makes the "Event horizon" puzzle possible, I will update the title of this issue and close it out.

As I mentioned before, solving the case of arbitrary values in their full generality is probably not feasible. However, please let me know if you have other examples of puzzles, or if you have concrete ideas for how such constraint could be implemented.

[^1]: https://github.com/sigh/Interactive-Sudoku-Solver/commit/3635d70743174c0a499baab51ea1509d87dfbcdd
