### ISSUE TITLE
Feature request: Constrain two sets of cells to the same composition of digits

### ISSUE THREAD

**Issue by dare-to-recurse** [sigh/Interactive-Sudoku-Solver#5]
Example:
Placing this constraint on the selections {r1c1,r1c2,r2c1,r2c2} and {r4c4,r5c5,r6c6,r7c7} limits the selections to contain the exact same set of **unspecified** digits, regardless of the ordering of these digits.

If this can easily be recreated using the currently implemented constraints (though I cannot see a way at the moment) then perhaps a small example on how to do so could be documented?

**Comment by sigh** [comment]
This is not currently possible, but may not be too hard to expose.

Can the digits in each set of cells repeat, or at they unique? If they are unique the underlying solver has the capability to handle such constraints (the `SameValues` handler in `handlers.js`). If the digits can repeat then it would need to be implemented.

**Comment by sigh** [comment]
This is not currently possible, but may not be too hard to expose.

Can the digits in each set of cells repeat, or at they unique? If they are unique the underlying solver has the capability to handle such constraints (the SameValues handler in handlers.js). If the digits can repeat then it would need to be implemented.

The other challenge is how to expose this in the UI, but maybe just allowing the user to select an even number of cells and taking the first and second half is sufficient.

Please provide an example of a puzzle with this constraint. I like to work with concrete example to know if the implementation is performant and fit-for-purpose.

**Comment by dare-to-recurse** [comment]
An example with this constraint is this sudoku: https://logic-masters.de/Raetselportal/Raetsel/zeigen.php?id=000HGS

Specifically rule 3 in the description, which also specifies that there may be duplicate digits.

Another idea for how to expose it in the UI might be to:
1. Have the user select a set of digits.
2. Press the "Add" button to begin applying the constraint.
3. Prompting the user to select a second set of the same size, with an "ok" or "complete" button on the prompt that is only enabled with a correctly sized selection.

**Comment by sigh** [comment]
Thanks, looks like that would require to allow repeated digits. I'll have a look at implementing it when I have time.
It will require expanding the `SameValues` handler to allow repeated digits, making that available as a new constraint and then exposing it in the UI.

I agree that your UI suggestion would be nice, however I'm trying to avoid more complex UI interactions from a time and maintenance point of view. After I implement this in the solver, I'll think more about possible options for UI.

**Comment by sigh** [comment]
This is implemented now in the "Lines & Regions" panel as "Same Value Sets". I generalised it so that it can support any number of equally sized sets. This makes it a bit easier to set up clone puzzles as well. The option to create 2 sets is only available when the number of cells selected is even.

Here is the "Copycat" puzzle you gave as an example. It still takes a few thousand guesses because the solver is not able to notice all the interactions that the same values rule has with the palindrome and zipper.

http://sigh.github.io/Interactive-Sudoku-Solver/?q=.Palindrome~R9C1~R8C1~R8C2~R7C3~R6C3~R5C2~R4C2~R3C3~R2C4~R1C5~R1C6~R1C7~R1C8~R2C8~R2C9.WhiteDot~R5C6~R5C5.BlackDot~R2C5~R3C5.BlackDot~R3C7~R3C8.Zipper~R8C3~R7C4~R8C5~R9C6~R8C7~R7C7~R6C8~R5C8~R4C7~R3C7~R2C7~R3C6~R3C5~R3C4~R4C4.SameValues~2~R9C1~R8C1~R8C2~R7C3~R6C3~R5C2~R4C2~R3C3~R2C4~R1C5~R1C6~R1C7~R1C8~R2C8~R2C9~R8C3~R7C4~R8C5~R9C6~R8C7~R7C7~R6C8~R5C8~R4C7~R3C7~R2C7~R3C6~R3C5~R3C4~R4C4.
